title: "人工言語 Fonel"        # サイト全体のタイトル。ブラウザのタブやSEOで使われます
description: 人工言語 Fonel(フォネル) のサイト  # サイトの説明文。検索エンジンなどに使われます

# Just the Docs 設定
theme: just-the-docs		# Jekyllテーマ名。ここでは「just-the-docs」を使用


# カスタムCSSの読み込み
sass:
  custom_css: assets/css/custom.scss

######just_the_docs:
######  custom_css:
######    - "assets/css/custom.css"

url: https://arixatos.github.io		# サイトの基本URL。GitHub PagesのURLを指定
baseurl: /fonel						# サイトのベースパス。リポジトリ名に合わせて設定


# ナビゲーションバー設定ブロック
navbar:
  title: Fonel						# ナビバー左上に表示されるサイトタイトル（ロゴ横のテキスト）
  logo:
    path: assets/img/logo.png		# ナビバーに表示するロゴ画像のパス
  links:							# ナビバーに表示するリンクリスト
    - title: GitHub					# 表示名
      url: https://github.com/arixatos/fonel  # リンク先URL


# サイトの補助的なリンク群（フッターなどに表示されることも）
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template  # テンプレートのGitHubリポジトリURL
