title: 人工言語 Fonel

##theme: just-the-docs
theme: minima  

plugins:
  - jekyll-feed
nav_enabled: true

# GitHub PagesのURLに合わせて設定
baseurl: "/fonel"  # ここはリポジトリ名に置き換えてください
url: "https://arixatos.github.io"

navbar:
  title: Fonel Project
  logo:
    path: assets/img/logo.png
  links:
    - title: GitHub
      url: https://github.com/arixatos/fonel
